// This file is auto-generated by Supabase.
// You can regenerate it with `npx supabase gen types typescript --project-id <your-project-id> > src/types/database.types.ts`
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      biosignals: {
        Row: {
          id: number
          session_id: string
          user_id: string
          timestamp: string
          heart_rate: number | null
          spo2: number | null
          temperature: number | null
          stress_score: number | null
          motion_score: number | null
          hrv: number | null
        }
        Insert: {
          id?: number
          session_id: string
          user_id: string
          timestamp?: string
          heart_rate?: number | null
          spo2?: number | null
          temperature?: number | null
          stress_score?: number | null
          motion_score?: number | null
          hrv?: number | null
        }
        Update: {
          id?: number
          session_id?: string
          user_id?: string
          timestamp?: string
          heart_rate?: number | null
          spo2?: number | null
          temperature?: number | null
          stress_score?: number | null
          motion_score?: number | null
          hrv?: number | null
        }
      }
      devices: {
        Row: {
          id: string
          user_id: string
          name: string
          model: string | null
          created_at: string
          settings: Json | null
        }
        Insert: {
          id?: string
          user_id: string
          name?: string
          model?: string | null
          created_at?: string
          settings?: Json | null
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          model?: string | null
          created_at?: string
          settings?: Json | null
        }
      }
      profiles: {
        Row: {
          id: string
          full_name: string | null
          updated_at: string | null
        }
        Insert: {
          id: string
          full_name?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          full_name?: string | null
          updated_at?: string | null
        }
      }
      sessions: {
        Row: {
          id: string
          user_id: string
          device_id: string | null
          start_time: string
          end_time: string | null
          notes: string | null
        }
        Insert: {
          id?: string
          user_id: string
          device_id?: string | null
          start_time?: string
          end_time?: string | null
          notes?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          device_id?: string | null
          start_time?: string
          end_time?: string | null
          notes?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      handle_new_user: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
