/*
# [Initial NeuraBand Schema]
This migration sets up the core tables for the NeuraBand application, including user profiles, devices, recording sessions, and biosignal data storage. It also establishes Row Level Security (RLS) to ensure data privacy and creates a trigger to automatically create a user profile upon signup.

## Query Description: [This script initializes the database structure for a multi-user environment. It creates four main tables: `profiles` for user metadata, `devices` for linking physical NeuraBand hardware to users, `sessions` for tracking recording periods, and `biosignals` for storing time-series sensor data. No existing data will be affected as these are new tables. RLS is enabled by default to prevent unauthorized data access.]

## Metadata:
- Schema-Category: ["Structural"]
- Impact-Level: ["Low"]
- Requires-Backup: [false]
- Reversible: [true]

## Structure Details:
- **Tables Created**: `profiles`, `devices`, `sessions`, `biosignals`
- **Functions Created**: `handle_new_user()`
- **Triggers Created**: `on_auth_user_created` on `auth.users`

## Security Implications:
- RLS Status: [Enabled] on all new tables.
- Policy Changes: [Yes], `SELECT`, `INSERT` policies are created for all new tables, scoped to the authenticated user.
- Auth Requirements: [All access requires a valid JWT from an authenticated user.]

## Performance Impact:
- Indexes: [Added] primary keys and foreign keys, which create indexes for efficient joins.
- Triggers: [Added] one trigger on `auth.users` for profile creation. Impact is minimal and only occurs on user creation.
- Estimated Impact: [Low performance impact on typical database operations. Write performance on the `biosignals` table will depend on ingestion rate.]
*/

-- 1. PROFILES TABLE
-- Stores public user data, linked to auth.users.
CREATE TABLE public.profiles (
  id UUID NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  updated_at TIMESTAMPTZ,
  full_name TEXT,
  avatar_url TEXT
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policies for profiles
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Trigger to create a profile for a new user
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 2. DEVICES TABLE
-- Stores information about each NeuraBand device.
CREATE TABLE public.devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  device_name TEXT NOT NULL,
  last_seen TIMESTAMPTZ
);

-- RLS for devices
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;

-- Policies for devices
CREATE POLICY "Users can view their own devices." ON public.devices FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert devices for themselves." ON public.devices FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own devices." ON public.devices FOR UPDATE USING (auth.uid() = user_id);


-- 3. SESSIONS TABLE
-- Represents a single recording session from a device.
CREATE TABLE public.sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  device_id BIGINT NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMPTZ
);

-- RLS for sessions
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

-- Policies for sessions
CREATE POLICY "Users can view their own sessions." ON public.sessions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create sessions for their own devices." ON public.sessions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own sessions." ON public.sessions FOR UPDATE USING (auth.uid() = user_id);


-- 4. BIOSIGNALS TABLE
-- Stores the time-series data for each session.
CREATE TABLE public.biosignals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES public.sessions(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  "timestamp" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  heart_rate INT,
  spo2 INT,
  temperature REAL,
  stress_score INT,
  motion_score INT,
  hrv REAL
);

-- RLS for biosignals
ALTER TABLE public.biosignals ENABLE ROW LEVEL SECURITY;

-- Policies for biosignals
CREATE POLICY "Users can view their own biosignal data." ON public.biosignals FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Authenticated users can insert their own biosignal data." ON public.biosignals FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Add indexes for performance
CREATE INDEX ON public.biosignals (session_id, "timestamp" DESC);
CREATE INDEX ON public.sessions (user_id, started_at DESC);
